import { useState } from 'react';
import { PageHeader, Card, Btn } from '../components/ui';
import { FileText, Download, Eye, RefreshCw, X } from 'lucide-react';

const reports = [
  { title: 'Parliamentary Briefing', desc: 'Q4 FY 2024–25 strategic overview for Ministry', lastGen: 'Today, 08:30 AM', format: 'PDF', size: '2.4 MB' },
  { title: 'National Mental Wellbeing Report', desc: 'Comprehensive state-wise wellbeing analysis', lastGen: 'Yesterday, 06:00 PM', format: 'PDF', size: '5.8 MB' },
  { title: 'State Performance Report — Maharashtra', desc: 'District-level KPIs and intervention outcomes', lastGen: '31 Mar 2025, 11:45 PM', format: 'XLSX', size: '1.2 MB' },
  { title: 'Resource Allocation Report', desc: 'Counselor and resource gap analysis nationwide', lastGen: '30 Mar 2025', format: 'PDF', size: '3.1 MB' },
  { title: 'Intervention Outcomes Report', desc: 'Before/after distress analysis and success rates', lastGen: '28 Mar 2025', format: 'PDF', size: '4.0 MB' },
];

function ParliamentaryBriefingModal({ onClose }: { onClose: () => void }) {
  return (
    <div className="fixed inset-0 z-50 bg-slate-900/50 backdrop-blur-sm flex items-center justify-center px-4">
      <div className="bg-white rounded-2xl shadow-2xl w-full max-w-3xl max-h-[85vh] overflow-y-auto">
        <div className="flex items-center justify-between px-8 py-5 border-b border-slate-200 sticky top-0 bg-white z-10">
          <div>
            <div className="text-[10px] text-slate-400 uppercase tracking-widest mb-0.5">Government of India — CONFIDENTIAL</div>
            <h2 className="text-lg font-bold text-slate-900">Parliamentary Briefing Note</h2>
          </div>
          <button onClick={onClose} className="text-slate-400 hover:text-slate-700 transition-colors">
            <X className="w-5 h-5" />
          </button>
        </div>
        <div className="px-8 py-6 text-sm text-slate-700 leading-relaxed space-y-5">
          <div className="grid grid-cols-3 gap-4 text-xs text-slate-500 border-b border-slate-100 pb-4">
            <div><span className="font-semibold">Prepared by:</span> Sahyog AI — Ministry of Social Justice & Empowerment</div>
            <div><span className="font-semibold">Date:</span> 1 April 2025</div>
            <div><span className="font-semibold">Classification:</span> Official Use Only</div>
          </div>
          <h3 className="font-bold text-slate-900 text-base">1. Executive Summary</h3>
          <p>The Sahyog AI platform monitors the mental wellbeing of <strong>1,24,200</strong> registered survivors of atrocities across <strong>18 states</strong>. The national average distress score has declined by 4.8% compared to the same period in FY 2023–24, indicating improved intervention coverage. However, <strong>four states — Bihar, Uttar Pradesh, Jharkhand, and Madhya Pradesh</strong> — continue to record distress scores above the critical threshold.</p>
          <h3 className="font-bold text-slate-900 text-base">2. Key Indicators</h3>
          <table className="w-full border border-slate-200 rounded-lg overflow-hidden text-xs">
            <thead><tr className="bg-slate-50">
              {['Indicator', 'FY 2023–24', 'FY 2024–25', 'Change'].map(h => <th key={h} className="px-4 py-2 text-left font-semibold text-slate-600">{h}</th>)}
            </tr></thead>
            <tbody>
              {[
                ['Avg. National Distress Score', '58.6', '54.2', '↓ 4.4'],
                ['Total Beneficiaries', '1,09,200', '1,24,200', '↑ 13.7%'],
                ['Intervention Coverage', '63.2%', '71.6%', '↑ 8.4%'],
                ['High-Risk Cases', '19,420', '18,240', '↓ 6.1%'],
              ].map(r => <tr key={r[0]} className="border-t border-slate-100">{r.map((c, i) => <td key={i} className={`px-4 py-2 ${i === 3 ? (c.startsWith('↓') ? 'text-emerald-600 font-semibold' : 'text-red-600 font-semibold') : ''}`}>{c}</td>)}</tr>)}
            </tbody>
          </table>
          <h3 className="font-bold text-slate-900 text-base">3. States Requiring Policy Attention</h3>
          <p>Bihar, Uttar Pradesh, and Jharkhand require legislative and resource-level intervention. The Sahyog AI platform identifies counselor shortfalls and trial delays as primary drivers of elevated distress scores in these states.</p>
          <h3 className="font-bold text-slate-900 text-base">4. Recommended Actions</h3>
          <ol className="list-decimal list-inside space-y-1 text-slate-700 ml-2">
            <li>Approve additional counselor deployment of 340 FTEs across 4 priority states.</li>
            <li>Direct MHA to review trial delays exceeding 180 days in 6 high-distress districts.</li>
            <li>Expand digital check-in infrastructure in Bihar (target: 85% coverage).</li>
          </ol>
          <div className="border-t border-slate-200 pt-4 text-xs text-slate-400 italic">
            This briefing is generated by the Sahyog AI platform using anonymized, AI-assisted analysis. All findings require verification by the nodal Ministry official before formal submission.
          </div>
        </div>
        <div className="flex justify-end gap-2 px-8 py-4 border-t border-slate-100">
          <Btn variant="secondary"><Download className="w-3.5 h-3.5" /> Download PDF</Btn>
          <Btn variant="primary">Submit to Ministry</Btn>
        </div>
      </div>
    </div>
  );
}

export default function Reports() {
  const [showBriefing, setShowBriefing] = useState(false);

  return (
    <div className="p-6 max-w-screen-xl mx-auto">
      <PageHeader title="Reports & Briefings" subtitle="Government report library — generate, preview and download" />
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-5">
        {reports.map(r => (
          <Card key={r.title} className="flex flex-col">
            <div className="flex items-start gap-3 mb-4 flex-1">
              <div className="w-10 h-10 rounded-lg bg-blue-50 flex items-center justify-center flex-shrink-0">
                <FileText className="w-5 h-5 text-blue-600" />
              </div>
              <div>
                <h3 className="text-sm font-semibold text-slate-800 mb-0.5">{r.title}</h3>
                <p className="text-xs text-slate-500 leading-tight">{r.desc}</p>
                <div className="flex items-center gap-2 mt-1.5">
                  <span className="text-[10px] bg-slate-100 text-slate-600 px-1.5 py-0.5 rounded font-mono">{r.format}</span>
                  <span className="text-[10px] text-slate-400">{r.size}</span>
                </div>
                <div className="text-[10px] text-slate-400 mt-1">Last: {r.lastGen}</div>
              </div>
            </div>
            <div className="flex gap-2 pt-3 border-t border-slate-100">
              <Btn size="xs" variant="secondary" onClick={() => r.title.includes('Parliamentary') && setShowBriefing(true)}>
                <Eye className="w-3 h-3" /> Preview
              </Btn>
              <Btn size="xs" variant="ghost"><RefreshCw className="w-3 h-3" /> Generate</Btn>
              <Btn size="xs" variant="ghost"><Download className="w-3 h-3" /> Download</Btn>
            </div>
          </Card>
        ))}
      </div>
      {showBriefing && <ParliamentaryBriefingModal onClose={() => setShowBriefing(false)} />}
    </div>
  );
}
